<?php

namespace MrConnect;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider as SP;

class MrConnectServiceProvider extends SP
{
    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot(): void
    {
        $this->loadConfig();
//        $this->loadRoutes();
//        $this->loadMigrations();
    }

    private function loadConfig(): void
    {
        $this->publishes(
            [
                __DIR__ . '/../config/mrconnect.php' => config_path('mrconnect.php'),
            ],
            'mrconnect-config'
        );
    }

    private function loadRoutes(): void
    {
        $this->loadRoutesFrom(__DIR__ . '/../routes/mrconnect.php');

        $this->publishes(
            [
                __DIR__ . '/../routes' => base_path('routes'),
            ],
            'mrconnect-routes'
        );
    }

    private function loadMigrations(): void
    {
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');

        $this->publishes(
            [
                __DIR__ . '/../database/migrations' => base_path('database/migrations'),
            ],
            'mrconnect-migrations'
        );
    }

    private function loadTranslations(): void
    {
        $this->loadTranslationsFrom(__DIR__ . '/../resources/lang', 'package-name-trans');

        $this->publishes(
            [
                __DIR__ . '/../resources/lang' => resource_path('lang'),
            ],
            'mrconnect-lang'
        );
    }

    private function loadCommands(): void
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
            ]);
        }
    }

    public function register()
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/mrconnect.php', 'mrconnect'
        );
        parent::register(); // TODO: Change the autogenerated stub
    }
}
